packages:
  - software/sccoda
  - software/replicates
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.43.2
  "@platforma-sdk/ui-vue": ^1.43.11
  "@platforma-sdk/workflow-tengo": ^5.2.2
  "@platforma-sdk/block-tools": ^2.6.6
  "@platforma-sdk/test": ^1.43.12
  "@platforma-sdk/tengo-builder": ^2.1.21
  "@platforma-sdk/package-builder": ^3.5.4
  "@platforma-sdk/eslint-config": ^1.1.0
  "@milaboratories/graph-maker": ^1.1.158
  "@platforma-sdk/blocks-deps-updater": ^2.0.0

  "@platforma-open/milaboratories.runenv-python-3": ^1.4.10

  "vue": ^3.5.12
  "vue-tsc": ^2.1.6

  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^5.4.11
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.27.9
